[package]
name = "music_manager_cli"
version = "0.1.0"
authors = ["Ryan Blecher <notryanb@gmail.com>"]
edition = "2018"

[[bin]]
name = "music_manager_cli"
path = "src/main.rs"

[dependencies]
music_manager = { path = "../music_manager" }
quicli = "0.4"
structopt = "0.2"
walkdir = "2"
