[package]
name = "music_manager"
version = "0.1.0"
authors = ["Ryan Blecher <notryanb@gmail.com>"]
edition = "2018"

[lib]
name = "music_manager_lib"
path = "src/lib.rs"

[dependencies]
diesel = { version = "1.3", features = ["postgres"] }
dotenv = "0.13.0"
id3 = "0.3"
walkdir = "2"